# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/specs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/specs.proto',
  package='specs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11proto/specs.proto\x12\x05specs\"I\n\x08\x42\x61nkData\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nshort_name\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05swift\x18\x04 \x01(\t\".\n\x06\x46ormat\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x13\n\x0breplacement\x18\x02 \x01(\t\",\n\x0bPatternData\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\".\n\x0eIbanFormatSpec\x12\x1c\n\x05print\x18\x01 \x01(\x0b\x32\r.specs.Format\"\xcc\x03\n\x08IbanSpec\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\r\x12\x14\n\x0c\x63ountry_name\x18\x02 \x01(\t\x12\x14\n\x0ciban_pattern\x18\x03 \x01(\t\x12\x14\n\x0c\x62\x62\x61n_pattern\x18\x04 \x01(\t\x12$\n\x1c\x63ountry_check_digits_pattern\x18\x05 \x01(\t\x12+\n\x0freserved_fields\x18\x06 \x01(\x0b\x32\x12.specs.PatternData\x12\x0e\n\x06length\x18\x07 \x01(\r\x12&\n\x07\x66ormats\x18\x08 \x01(\x0b\x32\x15.specs.IbanFormatSpec\x12\x13\n\x0b\x63heck_digit\x18\t \x01(\r\x12\x11\n\tbank_code\x18\n \x01(\r\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x0b \x01(\r\x12\x13\n\x0b\x62ranch_code\x18\x0c \x01(\r\x12\x14\n\x0c\x61\x63\x63ount_type\x18\r \x01(\r\x12\x1d\n\x15\x61\x63\x63ount_holder_number\x18\x0e \x01(\r\x12\x1e\n\x16\x62\x61lance_account_number\x18\x0f \x01(\r\x12\x15\n\rcurrency_code\x18\x10 \x01(\r\x12\x1c\n\x14owner_account_number\x18\x11 \x01(\r\"x\n\nIbansSpecs\x12+\n\x05specs\x18\x01 \x03(\x0b\x32\x1c.specs.IbansSpecs.SpecsEntry\x1a=\n\nSpecsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.specs.IbanSpec:\x02\x38\x01\"v\n\tBanksData\x12*\n\x05\x62\x61nks\x18\x01 \x03(\x0b\x32\x1b.specs.BanksData.BanksEntry\x1a=\n\nBanksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.specs.BankData:\x02\x38\x01\x62\x06proto3'
)

_BANKDATA = _descriptor.Descriptor(
  name='BankData',
  full_name='specs.BankData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='specs.BankData.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='specs.BankData.short_name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='specs.BankData.code', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='specs.BankData.swift', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=101,
)


_FORMAT = _descriptor.Descriptor(
  name='Format',
  full_name='specs.Format',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='specs.Format.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='specs.Format.replacement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=149,
)


_PATTERNDATA = _descriptor.Descriptor(
  name='PatternData',
  full_name='specs.PatternData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='specs.PatternData.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='specs.PatternData.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=195,
)


_IBANFORMATSPEC = _descriptor.Descriptor(
  name='IbanFormatSpec',
  full_name='specs.IbanFormatSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='print', full_name='specs.IbanFormatSpec.print', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=243,
)


_IBANSPEC = _descriptor.Descriptor(
  name='IbanSpec',
  full_name='specs.IbanSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_code', full_name='specs.IbanSpec.country_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_name', full_name='specs.IbanSpec.country_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iban_pattern', full_name='specs.IbanSpec.iban_pattern', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bban_pattern', full_name='specs.IbanSpec.bban_pattern', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_check_digits_pattern', full_name='specs.IbanSpec.country_check_digits_pattern', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reserved_fields', full_name='specs.IbanSpec.reserved_fields', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='specs.IbanSpec.length', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='formats', full_name='specs.IbanSpec.formats', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_digit', full_name='specs.IbanSpec.check_digit', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank_code', full_name='specs.IbanSpec.bank_code', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='specs.IbanSpec.account_number', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branch_code', full_name='specs.IbanSpec.branch_code', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_type', full_name='specs.IbanSpec.account_type', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_holder_number', full_name='specs.IbanSpec.account_holder_number', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance_account_number', full_name='specs.IbanSpec.balance_account_number', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency_code', full_name='specs.IbanSpec.currency_code', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_account_number', full_name='specs.IbanSpec.owner_account_number', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=706,
)


_IBANSSPECS_SPECSENTRY = _descriptor.Descriptor(
  name='SpecsEntry',
  full_name='specs.IbansSpecs.SpecsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='specs.IbansSpecs.SpecsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='specs.IbansSpecs.SpecsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=767,
  serialized_end=828,
)

_IBANSSPECS = _descriptor.Descriptor(
  name='IbansSpecs',
  full_name='specs.IbansSpecs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='specs', full_name='specs.IbansSpecs.specs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IBANSSPECS_SPECSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=828,
)


_BANKSDATA_BANKSENTRY = _descriptor.Descriptor(
  name='BanksEntry',
  full_name='specs.BanksData.BanksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='specs.BanksData.BanksEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='specs.BanksData.BanksEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=887,
  serialized_end=948,
)

_BANKSDATA = _descriptor.Descriptor(
  name='BanksData',
  full_name='specs.BanksData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='banks', full_name='specs.BanksData.banks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BANKSDATA_BANKSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=948,
)

_IBANFORMATSPEC.fields_by_name['print'].message_type = _FORMAT
_IBANSPEC.fields_by_name['reserved_fields'].message_type = _PATTERNDATA
_IBANSPEC.fields_by_name['formats'].message_type = _IBANFORMATSPEC
_IBANSSPECS_SPECSENTRY.fields_by_name['value'].message_type = _IBANSPEC
_IBANSSPECS_SPECSENTRY.containing_type = _IBANSSPECS
_IBANSSPECS.fields_by_name['specs'].message_type = _IBANSSPECS_SPECSENTRY
_BANKSDATA_BANKSENTRY.fields_by_name['value'].message_type = _BANKDATA
_BANKSDATA_BANKSENTRY.containing_type = _BANKSDATA
_BANKSDATA.fields_by_name['banks'].message_type = _BANKSDATA_BANKSENTRY
DESCRIPTOR.message_types_by_name['BankData'] = _BANKDATA
DESCRIPTOR.message_types_by_name['Format'] = _FORMAT
DESCRIPTOR.message_types_by_name['PatternData'] = _PATTERNDATA
DESCRIPTOR.message_types_by_name['IbanFormatSpec'] = _IBANFORMATSPEC
DESCRIPTOR.message_types_by_name['IbanSpec'] = _IBANSPEC
DESCRIPTOR.message_types_by_name['IbansSpecs'] = _IBANSSPECS
DESCRIPTOR.message_types_by_name['BanksData'] = _BANKSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BankData = _reflection.GeneratedProtocolMessageType('BankData', (_message.Message,), {
  'DESCRIPTOR' : _BANKDATA,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.BankData)
  })
_sym_db.RegisterMessage(BankData)

Format = _reflection.GeneratedProtocolMessageType('Format', (_message.Message,), {
  'DESCRIPTOR' : _FORMAT,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.Format)
  })
_sym_db.RegisterMessage(Format)

PatternData = _reflection.GeneratedProtocolMessageType('PatternData', (_message.Message,), {
  'DESCRIPTOR' : _PATTERNDATA,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.PatternData)
  })
_sym_db.RegisterMessage(PatternData)

IbanFormatSpec = _reflection.GeneratedProtocolMessageType('IbanFormatSpec', (_message.Message,), {
  'DESCRIPTOR' : _IBANFORMATSPEC,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.IbanFormatSpec)
  })
_sym_db.RegisterMessage(IbanFormatSpec)

IbanSpec = _reflection.GeneratedProtocolMessageType('IbanSpec', (_message.Message,), {
  'DESCRIPTOR' : _IBANSPEC,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.IbanSpec)
  })
_sym_db.RegisterMessage(IbanSpec)

IbansSpecs = _reflection.GeneratedProtocolMessageType('IbansSpecs', (_message.Message,), {

  'SpecsEntry' : _reflection.GeneratedProtocolMessageType('SpecsEntry', (_message.Message,), {
    'DESCRIPTOR' : _IBANSSPECS_SPECSENTRY,
    '__module__' : 'proto.specs_pb2'
    # @@protoc_insertion_point(class_scope:specs.IbansSpecs.SpecsEntry)
    })
  ,
  'DESCRIPTOR' : _IBANSSPECS,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.IbansSpecs)
  })
_sym_db.RegisterMessage(IbansSpecs)
_sym_db.RegisterMessage(IbansSpecs.SpecsEntry)

BanksData = _reflection.GeneratedProtocolMessageType('BanksData', (_message.Message,), {

  'BanksEntry' : _reflection.GeneratedProtocolMessageType('BanksEntry', (_message.Message,), {
    'DESCRIPTOR' : _BANKSDATA_BANKSENTRY,
    '__module__' : 'proto.specs_pb2'
    # @@protoc_insertion_point(class_scope:specs.BanksData.BanksEntry)
    })
  ,
  'DESCRIPTOR' : _BANKSDATA,
  '__module__' : 'proto.specs_pb2'
  # @@protoc_insertion_point(class_scope:specs.BanksData)
  })
_sym_db.RegisterMessage(BanksData)
_sym_db.RegisterMessage(BanksData.BanksEntry)


_IBANSSPECS_SPECSENTRY._options = None
_BANKSDATA_BANKSENTRY._options = None
# @@protoc_insertion_point(module_scope)
